"""Exercise library (200+), programs (50+), and foods for WOS4E."""
from urllib.parse import quote_plus

CATS = {
    "strength": "Strength",
    "power": "Power / Olympic",
    "aerobic": "Aerobic / Cardio",
    "plyo": "Plyometric",
    "mobility": "Mobility / Flexibility",
    "core": "Core",
}


def yt(name: str) -> str:
    return f"https://www.youtube.com/results?search_query={quote_plus(name + ' proper form')}"


_RAW = [
    ('sq', 'Back Squat', 'strength', 'Barbell', 'Quads, Glutes'),
    ('fsq', 'Front Squat', 'strength', 'Barbell', 'Quads, Core'),
    ('gsq', 'Goblet Squat', 'strength', 'Dumbbell', 'Quads, Glutes'),
    ('bsq', 'Bulgarian Split Squat', 'strength', 'Dumbbell', 'Quads, Glutes'),
    ('hack', 'Hack Squat', 'strength', 'Machine', 'Quads'),
    ('legpress', 'Leg Press', 'strength', 'Machine', 'Quads, Glutes'),
    ('legext', 'Leg Extension', 'strength', 'Machine', 'Quads'),
    ('legcurl', 'Lying Leg Curl', 'strength', 'Machine', 'Hamstrings'),
    ('seatedcurl', 'Seated Leg Curl', 'strength', 'Machine', 'Hamstrings'),
    ('dl', 'Conventional Deadlift', 'strength', 'Barbell', 'Posterior chain'),
    ('sumo', 'Sumo Deadlift', 'strength', 'Barbell', 'Glutes, Quads'),
    ('rdl', 'Romanian Deadlift', 'strength', 'Barbell', 'Hamstrings, Glutes'),
    ('srdl', 'Single-Leg RDL', 'strength', 'Dumbbell', 'Hamstrings, Balance'),
    ('trapbar', 'Trap Bar Deadlift', 'strength', 'Trap bar', 'Full lower'),
    ('hipthrust', 'Barbell Hip Thrust', 'strength', 'Barbell', 'Glutes'),
    ('ghr', 'Glute-Ham Raise', 'strength', 'Machine', 'Hamstrings, Glutes'),
    ('lunge', 'Walking Lunge', 'strength', 'Dumbbell', 'Quads, Glutes'),
    ('rlunge', 'Reverse Lunge', 'strength', 'Dumbbell', 'Quads, Glutes'),
    ('slunge', 'Side Lunge', 'strength', 'Dumbbell', 'Adductors, Quads'),
    ('stepup', 'Step-Up', 'strength', 'Dumbbell', 'Quads, Glutes'),
    ('calfraise', 'Standing Calf Raise', 'strength', 'Machine', 'Calves'),
    ('seatedcalf', 'Seated Calf Raise', 'strength', 'Machine', 'Soleus'),
    ('donkeycalf', 'Donkey Calf Raise', 'strength', 'Machine', 'Calves'),
    ('goodmorn', 'Good Morning', 'strength', 'Barbell', 'Hamstrings, Back'),
    ('nordic', 'Nordic Hamstring Curl', 'strength', 'Bodyweight', 'Hamstrings'),
    ('bp', 'Bench Press', 'strength', 'Barbell', 'Chest, Triceps'),
    ('ibp', 'Incline Bench Press', 'strength', 'Barbell', 'Upper chest'),
    ('dbp', 'Decline Bench Press', 'strength', 'Barbell', 'Lower chest'),
    ('dbbp', 'Dumbbell Bench Press', 'strength', 'Dumbbell', 'Chest'),
    ('idbbp', 'Incline Dumbbell Press', 'strength', 'Dumbbell', 'Upper chest'),
    ('fly', 'Dumbbell Fly', 'strength', 'Dumbbell', 'Chest'),
    ('ifly', 'Incline Dumbbell Fly', 'strength', 'Dumbbell', 'Upper chest'),
    ('cablefly', 'Cable Fly', 'strength', 'Cable', 'Chest'),
    ('pecdeck', 'Pec Deck', 'strength', 'Machine', 'Chest'),
    ('pushup', 'Push-Up', 'strength', 'Bodyweight', 'Chest, Triceps'),
    ('dipp', 'Chest Dip', 'strength', 'Bodyweight', 'Chest, Triceps'),
    ('ohp', 'Overhead Press', 'strength', 'Barbell', 'Shoulders, Triceps'),
    ('dohp', 'Dumbbell Shoulder Press', 'strength', 'Dumbbell', 'Shoulders'),
    ('arnpress', 'Arnold Press', 'strength', 'Dumbbell', 'Shoulders'),
    ('latraise', 'Lateral Raise', 'strength', 'Dumbbell', 'Side delts'),
    ('frontraise', 'Front Raise', 'strength', 'Dumbbell', 'Front delts'),
    ('reardelt', 'Rear Delt Fly', 'strength', 'Dumbbell', 'Rear delts'),
    ('facepull', 'Face Pull', 'strength', 'Cable', 'Rear delts, Rotators'),
    ('uprightrow', 'Upright Row', 'strength', 'Barbell', 'Shoulders, Traps'),
    ('shrug', 'Barbell Shrug', 'strength', 'Barbell', 'Traps'),
    ('dbshrug', 'Dumbbell Shrug', 'strength', 'Dumbbell', 'Traps'),
    ('triceps', 'Tricep Pushdown', 'strength', 'Cable', 'Triceps'),
    ('ohtri', 'Overhead Tricep Extension', 'strength', 'Dumbbell', 'Triceps'),
    ('skull', 'Skull Crusher', 'strength', 'Barbell', 'Triceps'),
    ('closebp', 'Close-Grip Bench Press', 'strength', 'Barbell', 'Triceps, Chest'),
    ('kickback', 'Tricep Kickback', 'strength', 'Dumbbell', 'Triceps'),
    ('diamond', 'Diamond Push-Up', 'strength', 'Bodyweight', 'Triceps'),
    ('pullup', 'Pull-Up', 'strength', 'Bodyweight', 'Lats, Biceps'),
    ('chinup', 'Chin-Up', 'strength', 'Bodyweight', 'Lats, Biceps'),
    ('latpd', 'Lat Pulldown', 'strength', 'Cable', 'Lats'),
    ('cgrlat', 'Close-Grip Lat Pulldown', 'strength', 'Cable', 'Lats, Biceps'),
    ('row', 'Barbell Row', 'strength', 'Barbell', 'Back, Biceps'),
    ('pendlay', 'Pendlay Row', 'strength', 'Barbell', 'Back'),
    ('yates', 'Yates Row', 'strength', 'Barbell', 'Back'),
    ('dbrow', 'One-Arm Dumbbell Row', 'strength', 'Dumbbell', 'Back'),
    ('cblerow', 'Seated Cable Row', 'strength', 'Cable', 'Back'),
    ('chestrow', 'Chest-Supported Row', 'strength', 'Machine', 'Back'),
    ('tbar', 'T-Bar Row', 'strength', 'Barbell', 'Back'),
    ('invrow', 'Inverted Row', 'strength', 'Bodyweight', 'Back, Biceps'),
    ('facepull2', 'Band Face Pull', 'strength', 'Band', 'Rear delts'),
    ('curl', 'Barbell Curl', 'strength', 'Barbell', 'Biceps'),
    ('dbcurl', 'Dumbbell Curl', 'strength', 'Dumbbell', 'Biceps'),
    ('hamcurl', 'Hammer Curl', 'strength', 'Dumbbell', 'Brachialis'),
    ('preacher', 'Preacher Curl', 'strength', 'Barbell', 'Biceps'),
    ('concurl', 'Concentration Curl', 'strength', 'Dumbbell', 'Biceps'),
    ('cablecurl', 'Cable Curl', 'strength', 'Cable', 'Biceps'),
    ('inclcurl', 'Incline Dumbbell Curl', 'strength', 'Dumbbell', 'Biceps'),
    ('revcurl', 'Reverse Curl', 'strength', 'Barbell', 'Forearms, Biceps'),
    ('wristcurl', 'Wrist Curl', 'strength', 'Barbell', 'Forearms'),
    ('farmers', 'Farmers Carry', 'strength', 'Dumbbell', 'Grip, Core, Traps'),
    ('chestpress', 'Machine Chest Press', 'strength', 'Machine', 'Chest'),
    ('shpressm', 'Machine Shoulder Press', 'strength', 'Machine', 'Shoulders'),
    ('legabduct', 'Hip Abduction', 'strength', 'Machine', 'Glute medius'),
    ('legadduct', 'Hip Adduction', 'strength', 'Machine', 'Adductors'),
    ('backext', 'Back Extension', 'strength', 'Machine', 'Erectors'),
    ('hyperext', 'Hyperextension', 'strength', 'Bench', 'Erectors, Glutes'),
    ('cablekick', 'Cable Glute Kickback', 'strength', 'Cable', 'Glutes'),
    ('pullover', 'Dumbbell Pullover', 'strength', 'Dumbbell', 'Lats, Chest'),
    ('landmine', 'Landmine Press', 'strength', 'Barbell', 'Shoulders, Core'),
    ('lmrow', 'Landmine Row', 'strength', 'Barbell', 'Back'),
    ('sissy', 'Sissy Squat', 'strength', 'Bodyweight', 'Quads'),
    ('pistol', 'Pistol Squat', 'strength', 'Bodyweight', 'Quads, Balance'),
    ('wallsit', 'Wall Sit', 'strength', 'Bodyweight', 'Quads'),
    ('pc', 'Power Clean', 'power', 'Barbell', 'Full body'),
    ('hpc', 'Hang Power Clean', 'power', 'Barbell', 'Full body'),
    ('snatch', 'Power Snatch', 'power', 'Barbell', 'Full body'),
    ('hsnatch', 'Hang Snatch', 'power', 'Barbell', 'Full body'),
    ('cj', 'Clean and Jerk', 'power', 'Barbell', 'Full body'),
    ('pushj', 'Push Jerk', 'power', 'Barbell', 'Shoulders, Legs'),
    ('splitj', 'Split Jerk', 'power', 'Barbell', 'Shoulders, Legs'),
    ('pushpress', 'Push Press', 'power', 'Barbell', 'Shoulders, Legs'),
    ('mthruster', 'Dumbbell Thruster', 'power', 'Dumbbell', 'Full body'),
    ('kbswing', 'Kettlebell Swing', 'power', 'Kettlebell', 'Hips, Posterior'),
    ('kbsnatch', 'Kettlebell Snatch', 'power', 'Kettlebell', 'Full body'),
    ('kbclean', 'Kettlebell Clean', 'power', 'Kettlebell', 'Hips, Upper'),
    ('medballsl', 'Medicine Ball Slam', 'power', 'Med ball', 'Core, Power'),
    ('wallball', 'Wall Ball', 'power', 'Med ball', 'Legs, Shoulders'),
    ('broadjump', 'Broad Jump', 'power', 'Bodyweight', 'Legs, Power'),
    ('boxjump', 'Box Jump', 'plyo', 'Box', 'Legs, Power'),
    ('dboxjump', 'Depth Jump', 'plyo', 'Box', 'Legs, Reactive'),
    ('burpee', 'Burpee', 'plyo', 'Bodyweight', 'Full body'),
    ('burpeeuj', 'Burpee Box Jump', 'plyo', 'Box', 'Full body'),
    ('mountain', 'Mountain Climber', 'plyo', 'Bodyweight', 'Core, Cardio'),
    ('jknee', 'Jumping Knee Tuck', 'plyo', 'Bodyweight', 'Legs, Core'),
    ('skater', 'Skater Jump', 'plyo', 'Bodyweight', 'Lateral power'),
    ('latbound', 'Lateral Bound', 'plyo', 'Bodyweight', 'Lateral power'),
    ('sprint', 'Sprint', 'plyo', 'None', 'Speed, Power'),
    ('hsprint', 'Hill Sprint', 'plyo', 'None', 'Legs, Power'),
    ('clapush', 'Clapping Push-Up', 'plyo', 'Bodyweight', 'Chest, Power'),
    ('plyolunge', 'Jumping Lunge', 'plyo', 'Bodyweight', 'Legs'),
    ('squatjump', 'Squat Jump', 'plyo', 'Bodyweight', 'Legs'),
    ('starjump', 'Star Jump', 'plyo', 'Bodyweight', 'Full body'),
    ('run', 'Running / Jog', 'aerobic', 'None', 'Cardio'),
    ('tread', 'Treadmill Run', 'aerobic', 'Treadmill', 'Cardio'),
    ('bike', 'Stationary Bike', 'aerobic', 'Bike', 'Cardio, Legs'),
    ('abike', 'Assault Bike', 'aerobic', 'Assault bike', 'Cardio, Full'),
    ('rowm', 'Rowing Machine', 'aerobic', 'Rower', 'Cardio, Back'),
    ('ski', 'SkiErg', 'aerobic', 'SkiErg', 'Cardio, Upper'),
    ('swim', 'Swimming', 'aerobic', 'Pool', 'Full body'),
    ('walk', 'Brisk Walk', 'aerobic', 'None', 'Cardio'),
    ('hik', 'Hiking', 'aerobic', 'None', 'Cardio, Legs'),
    ('ellipt', 'Elliptical', 'aerobic', 'Machine', 'Cardio'),
    ('stair', 'Stair Climber', 'aerobic', 'Machine', 'Cardio, Legs'),
    ('jumprope', 'Jump Rope', 'aerobic', 'Rope', 'Cardio, Calves'),
    ('shadow', 'Shadow Boxing', 'aerobic', 'None', 'Cardio, Upper'),
    ('dance', 'Dance Cardio', 'aerobic', 'None', 'Cardio'),
    ('hiit', 'HIIT Circuit', 'aerobic', 'Various', 'Cardio, Conditioning'),
    ('plank', 'Plank', 'core', 'Bodyweight', 'Core'),
    ('splank', 'Side Plank', 'core', 'Bodyweight', 'Obliques'),
    ('deadbug', 'Dead Bug', 'core', 'Bodyweight', 'Core stability'),
    ('bird', 'Bird Dog', 'core', 'Bodyweight', 'Core, Back'),
    ('crunch', 'Crunch', 'core', 'Bodyweight', 'Abs'),
    ('bicycle', 'Bicycle Crunch', 'core', 'Bodyweight', 'Abs, Obliques'),
    ('legraise', 'Hanging Leg Raise', 'core', 'Bar', 'Lower abs'),
    ('rknee', 'Hanging Knee Raise', 'core', 'Bar', 'Lower abs'),
    ('toesbar', 'Toes-to-Bar', 'core', 'Bar', 'Abs, Grip'),
    ('abwheel', 'Ab Wheel Rollout', 'core', 'Ab wheel', 'Core'),
    ('pallof', 'Pallof Press', 'core', 'Cable', 'Anti-rotation'),
    ('russiantw', 'Russian Twist', 'core', 'Med ball', 'Obliques'),
    ('woodchop', 'Cable Woodchop', 'core', 'Cable', 'Obliques, Core'),
    ('hollow', 'Hollow Body Hold', 'core', 'Bodyweight', 'Abs'),
    ('vup', 'V-Up', 'core', 'Bodyweight', 'Abs'),
    ('superman', 'Superman Hold', 'core', 'Bodyweight', 'Erectors'),
    ('copenh', 'Copenhagen Plank', 'core', 'Bodyweight', 'Adductors, Core'),
    ('dragon', 'Dragon Flag', 'core', 'Bodyweight', 'Abs advanced'),
    ('catcow', 'Cat-Cow Stretch', 'mobility', 'Bodyweight', 'Spine'),
    ('worldgreat', 'Worlds Greatest Stretch', 'mobility', 'Bodyweight', 'Hips, T-spine'),
    ('hipflex', 'Hip Flexor Stretch', 'mobility', 'Bodyweight', 'Hip flexors'),
    ('pigeon', 'Pigeon Pose', 'mobility', 'Bodyweight', 'Glutes, Hips'),
    ('couch', 'Couch Stretch', 'mobility', 'Bodyweight', 'Hip flexors, Quads'),
    ('hamstretch', 'Standing Hamstring Stretch', 'mobility', 'Bodyweight', 'Hamstrings'),
    ('chestopen', 'Doorway Chest Stretch', 'mobility', 'Bodyweight', 'Chest, Shoulders'),
    ('thread', 'Thread the Needle', 'mobility', 'Bodyweight', 'T-spine'),
    ('ninenine', '90/90 Hip Stretch', 'mobility', 'Bodyweight', 'Hips'),
    ('ankle', 'Ankle Mobility Drill', 'mobility', 'Bodyweight', 'Ankles'),
    ('scapula', 'Scapular Pull-Up', 'mobility', 'Bar', 'Scapula'),
    ('banddisloc', 'Band Dislocate', 'mobility', 'Band', 'Shoulders'),
    ('foamroll', 'Foam Roll Quads', 'mobility', 'Foam roller', 'Recovery'),
    ('child', 'Childs Pose', 'mobility', 'Bodyweight', 'Back, Hips'),
    ('downward', 'Downward Dog', 'mobility', 'Bodyweight', 'Hamstrings, Shoulders'),
    ('zercher', 'Zercher Squat', 'strength', 'Barbell', 'Quads, Core'),
    ('boxsq', 'Box Squat', 'strength', 'Barbell', 'Quads, Glutes'),
    ('pause_sq', 'Paused Squat', 'strength', 'Barbell', 'Quads'),
    ('tempo_bp', 'Tempo Bench Press', 'strength', 'Barbell', 'Chest'),
    ('spoto', 'Spoto Press', 'strength', 'Barbell', 'Chest'),
    ('floorpress', 'Floor Press', 'strength', 'Barbell', 'Chest, Triceps'),
    ('jmpress', 'JM Press', 'strength', 'Barbell', 'Triceps'),
    ('meadows', 'Meadows Row', 'strength', 'Barbell', 'Back'),
    ('sealrow', 'Seal Row', 'strength', 'Barbell', 'Back'),
    ('kroc', 'Kroc Row', 'strength', 'Dumbbell', 'Back, Grip'),
    ('zottman', 'Zottman Curl', 'strength', 'Dumbbell', 'Biceps, Forearms'),
    ('spider', 'Spider Curl', 'strength', 'Dumbbell', 'Biceps'),
    ('bayesian', 'Bayesian Cable Curl', 'strength', 'Cable', 'Biceps'),
    ('overhead_c', 'Cable Overhead Extension', 'strength', 'Cable', 'Triceps'),
    ('ropepush', 'Rope Pushdown', 'strength', 'Cable', 'Triceps'),
    ('crossbody', 'Cross-Body Hammer Curl', 'strength', 'Dumbbell', 'Brachialis'),
    ('lu_raise', 'Lu Raise', 'strength', 'Dumbbell', 'Side delts'),
    ('scottpress', 'Scott Press', 'strength', 'Dumbbell', 'Shoulders'),
    ('cuban', 'Cuban Press', 'strength', 'Dumbbell', 'Rotators, Shoulders'),
    ('yraise', 'Y-Raise', 'strength', 'Dumbbell', 'Lower traps'),
    ('prone_y', 'Prone Y Raise', 'strength', 'Dumbbell', 'Lower traps'),
    ('prone_t', 'Prone T Raise', 'strength', 'Dumbbell', 'Rear delts'),
    ('prone_w', 'Prone W Raise', 'strength', 'Dumbbell', 'Rotators'),
    ('bandpull', 'Band Pull-Apart', 'strength', 'Band', 'Rear delts'),
    ('sledpush', 'Sled Push', 'strength', 'Sled', 'Legs, Conditioning'),
    ('sledpull', 'Sled Pull', 'strength', 'Sled', 'Posterior, Grip'),
    ('prowler', 'Prowler Push', 'strength', 'Prowler', 'Legs, Conditioning'),
    ('tireflip', 'Tire Flip', 'power', 'Tire', 'Full body'),
    ('atlas', 'Atlas Stone Load', 'power', 'Stone', 'Full body'),
    ('yoke', 'Yoke Walk', 'strength', 'Yoke', 'Core, Legs'),
    ('logpress', 'Log Press', 'power', 'Log', 'Shoulders'),
    ('axle_dl', 'Axle Deadlift', 'strength', 'Axle', 'Posterior, Grip'),
    ('strictpress', 'Strict Press', 'strength', 'Barbell', 'Shoulders'),
    ('behindneck', 'Behind-the-Neck Press', 'strength', 'Barbell', 'Shoulders'),
    ('bradford', 'Bradford Press', 'strength', 'Barbell', 'Shoulders'),
    ('sots', 'Sots Press', 'power', 'Barbell', 'Shoulders, Mobility'),
    ('oh_squat', 'Overhead Squat', 'power', 'Barbell', 'Full body, Mobility'),
    ('snatchbal', 'Snatch Balance', 'power', 'Barbell', 'Speed, Mobility'),
    ('muscle_sn', 'Muscle Snatch', 'power', 'Barbell', 'Upper, Technique'),
    ('muscle_cl', 'Muscle Clean', 'power', 'Barbell', 'Upper, Technique'),
    ('highpull', 'Snatch High Pull', 'power', 'Barbell', 'Traps, Power'),
    ('cleanpull', 'Clean Pull', 'power', 'Barbell', 'Posterior, Power'),
    ('block_cl', 'Block Clean', 'power', 'Barbell', 'Power'),
    ('block_sn', 'Block Snatch', 'power', 'Barbell', 'Power'),
    ('hang_cl', 'Hang Clean', 'power', 'Barbell', 'Power'),
    ('pwrjerk', 'Power Jerk', 'power', 'Barbell', 'Shoulders, Legs'),
    ('split_cl', 'Split Clean', 'power', 'Barbell', 'Power, Legs'),
    ('db_snatch', 'Dumbbell Snatch', 'power', 'Dumbbell', 'Full body'),
    ('db_clean', 'Dumbbell Clean', 'power', 'Dumbbell', 'Full body'),
    ('kb_goblet', 'Kettlebell Goblet Squat', 'strength', 'Kettlebell', 'Quads'),
    ('kb_row', 'Kettlebell Row', 'strength', 'Kettlebell', 'Back'),
    ('kb_press', 'Kettlebell Press', 'strength', 'Kettlebell', 'Shoulders'),
    ('kb_tgu', 'Turkish Get-Up', 'strength', 'Kettlebell', 'Full body, Core'),
    ('kb_windmill', 'Kettlebell Windmill', 'core', 'Kettlebell', 'Core, Shoulders'),
    ('ring_dip', 'Ring Dip', 'strength', 'Rings', 'Chest, Triceps'),
    ('ring_row', 'Ring Row', 'strength', 'Rings', 'Back'),
    ('muscleup', 'Muscle-Up', 'power', 'Bar/Rings', 'Full upper'),
    ('hspu', 'Handstand Push-Up', 'strength', 'Bodyweight', 'Shoulders'),
    ('l_sit', 'L-Sit', 'core', 'Bodyweight', 'Core, Hip flexors'),
    ('front_lever', 'Front Lever Progressions', 'strength', 'Bar', 'Core, Lats'),
    ('back_lever', 'Back Lever Progressions', 'strength', 'Bar', 'Shoulders, Core'),
    ('planche', 'Planche Progressions', 'strength', 'Bodyweight', 'Shoulders, Core'),
]

EXERCISES = [
    {"id": r[0], "name": r[1], "cat": r[2], "equip": r[3], "muscles": r[4], "video": yt(r[1])}
    for r in _RAW
]


def ex_by_id(eid: str):
    for e in EXERCISES:
        if e["id"] == eid:
            return e
    return None


def _p(label, typ, items):
    return {"label": label, "type": typ, "items": items}


def _i(ex, sets=3, reps=8, rest=90):
    return {"ex": ex, "sets": sets, "reps": reps, "rest": rest}



PROGRAMS = {
    "beg_fb_a": _p("Beginner Full Body A", "strength", [_i("sq",3,8,90), _i("bp",3,8,90), _i("row",3,8,90), _i("ohp",2,10,60), _i("plank",3,30,45)]),
    "beg_fb_b": _p("Beginner Full Body B", "strength", [_i("rdl",3,8,90), _i("dbbp",3,10,90), _i("latpd",3,10,90), _i("lunge",3,10,60), _i("deadbug",3,10,45)]),
    "beg_fb_c": _p("Beginner Full Body C", "strength", [_i("gsq",3,12,60), _i("pushup",3,10,60), _i("dbrow",3,10,60), _i("latraise",3,12,45), _i("bird",3,10,45)]),
    "beg_upper": _p("Beginner Upper Body", "strength", [_i("dbbp",3,10,90), _i("latpd",3,10,90), _i("dohp",3,10,60), _i("dbrow",3,10,60), _i("dbcurl",2,12,45), _i("triceps",2,12,45)]),
    "beg_lower": _p("Beginner Lower Body", "strength", [_i("gsq",3,12,90), _i("rdl",3,10,90), _i("lunge",3,10,60), _i("legcurl",3,12,60), _i("calfraise",3,15,45)]),
    "int_ul_upper": _p("Upper / Lower — Upper A", "strength", [_i("bp",4,6,120), _i("row",4,6,120), _i("ohp",3,8,90), _i("pullup",3,8,90), _i("curl",3,12,60), _i("triceps",3,12,60)]),
    "int_ul_lower": _p("Upper / Lower — Lower A", "strength", [_i("sq",4,6,150), _i("rdl",3,8,120), _i("legpress",3,10,90), _i("legcurl",3,12,60), _i("calfraise",4,12,45)]),
    "int_ul_upper_b": _p("Upper / Lower — Upper B", "strength", [_i("ibp",4,8,120), _i("cblerow",4,8,90), _i("dohp",3,10,90), _i("latpd",3,10,90), _i("facepull",3,15,45), _i("hamcurl",3,12,45)]),
    "int_ul_lower_b": _p("Upper / Lower — Lower B", "strength", [_i("trapbar",4,6,150), _i("bsq",3,8,90), _i("hipthrust",3,10,90), _i("legext",3,12,60), _i("seatedcalf",4,12,45)]),
    "ppl_push": _p("Push / Pull / Legs — Push", "strength", [_i("bp",4,6,120), _i("ohp",3,8,90), _i("idbbp",3,10,90), _i("latraise",3,15,45), _i("triceps",3,12,60), _i("ohtri",3,12,60)]),
    "ppl_pull": _p("Push / Pull / Legs — Pull", "strength", [_i("dl",3,5,180), _i("pullup",3,8,90), _i("row",4,8,90), _i("facepull",3,15,45), _i("curl",3,12,60), _i("hamcurl",3,12,45)]),
    "ppl_legs": _p("Push / Pull / Legs — Legs", "strength", [_i("sq",4,6,150), _i("rdl",3,8,120), _i("lunge",3,10,90), _i("legcurl",3,12,60), _i("calfraise",4,12,45), _i("plank",3,45,45)]),
    "ppl_push_b": _p("PPL Push B (hypertrophy)", "strength", [_i("ibp",4,8,90), _i("dohp",3,10,90), _i("cablefly",3,12,60), _i("latraise",4,15,45), _i("skull",3,12,60), _i("kickback",3,12,45)]),
    "ppl_pull_b": _p("PPL Pull B (hypertrophy)", "strength", [_i("latpd",4,10,90), _i("cblerow",4,10,90), _i("dbrow",3,12,60), _i("reardelt",3,15,45), _i("preacher",3,12,60), _i("revcurl",3,12,45)]),
    "ppl_legs_b": _p("PPL Legs B (hypertrophy)", "strength", [_i("fsq",4,8,120), _i("srdl",3,10,90), _i("legpress",3,12,90), _i("legext",3,15,60), _i("legcurl",3,12,60), _i("seatedcalf",4,15,45)]),
    "str_5x5": _p("Starting Strength Style 5x5", "strength", [_i("sq",5,5,180), _i("bp",5,5,180), _i("dl",1,5,180)]),
    "str_5x5_b": _p("Starting Strength Style B", "strength", [_i("sq",5,5,180), _i("ohp",5,5,150), _i("row",5,5,150)]),
    "str_texas": _p("Texas Method Volume Day", "strength", [_i("sq",5,5,180), _i("bp",5,5,180), _i("row",5,5,150)]),
    "str_intensity": _p("Heavy Singles Focus", "strength", [_i("sq",5,1,240), _i("bp",5,1,240), _i("dl",3,1,240)]),
    "str_pause": _p("Paused Strength Day", "strength", [_i("sq",4,3,180), _i("bp",4,3,180), _i("rdl",3,5,150), _i("ohp",3,5,120)]),
    "oly_intro": _p("Olympic Lifting Intro", "power", [_i("hpc",5,3,120), _i("hsnatch",5,2,120), _i("pushpress",4,3,90), _i("fsq",3,5,120)]),
    "oly_clean": _p("Clean Focus Session", "power", [_i("pc",6,2,150), _i("hpc",4,3,120), _i("fsq",4,3,120), _i("pushj",4,2,120)]),
    "oly_snatch": _p("Snatch Focus Session", "power", [_i("snatch",6,2,150), _i("hsnatch",4,3,120), _i("ohp",3,5,90)]),
    "power_kb": _p("Kettlebell Power", "power", [_i("kbswing",5,15,60), _i("kbclean",4,8,60), _i("kbsnatch",4,6,60), _i("mthruster",3,10,60)]),
    "power_ath": _p("Athletic Power Day", "power", [_i("boxjump",5,3,90), _i("pc",5,3,120), _i("broadjump",4,3,90), _i("medballsl",4,8,60), _i("sprint",6,1,90)]),
    "hyp_chest": _p("Chest Hypertrophy", "strength", [_i("bp",4,8,90), _i("idbbp",3,10,90), _i("cablefly",3,12,60), _i("dipp",3,10,90), _i("pushup",2,15,45)]),
    "hyp_back": _p("Back Hypertrophy", "strength", [_i("pullup",4,8,90), _i("row",4,8,90), _i("latpd",3,10,60), _i("cblerow",3,12,60), _i("facepull",3,15,45)]),
    "hyp_shoulders": _p("Shoulder Hypertrophy", "strength", [_i("ohp",4,8,90), _i("latraise",4,15,45), _i("reardelt",3,15,45), _i("frontraise",3,12,45), _i("facepull",3,15,45)]),
    "hyp_arms": _p("Arms Hypertrophy", "strength", [_i("curl",3,10,60), _i("skull",3,10,60), _i("hamcurl",3,12,45), _i("triceps",3,12,45), _i("preacher",3,12,45), _i("ohtri",3,12,45)]),
    "hyp_legs": _p("Leg Hypertrophy", "strength", [_i("sq",4,8,120), _i("rdl",3,10,90), _i("legpress",3,12,90), _i("legext",3,15,60), _i("legcurl",3,12,60), _i("calfraise",4,15,45)]),
    "hyp_glutes": _p("Glute Focus", "strength", [_i("hipthrust",4,10,90), _i("bsq",3,10,90), _i("rdl",3,10,90), _i("cablekick",3,15,45), _i("legabduct",3,15,45)]),
    "cardio_easy": _p("Easy Aerobic Base", "aerobic", [_i("walk",1,40,0), _i("bike",1,20,0)]),
    "cardio_zone2": _p("Zone 2 Cardio", "aerobic", [_i("run",1,45,0)]),
    "cardio_row": _p("Rowing Endurance", "aerobic", [_i("rowm",1,30,0), _i("plank",3,45,30)]),
    "cardio_hiit": _p("HIIT Intervals", "aerobic", [_i("abike",8,20,40), _i("burpee",4,10,60)]),
    "cardio_mixed": _p("Mixed Conditioning", "aerobic", [_i("rowm",1,10,60), _i("boxjump",4,5,60), _i("kbswing",4,15,45), _i("burpee",3,10,45)]),
    "cardio_swim": _p("Swim Session", "aerobic", [_i("swim",1,30,0)]),
    "core_basic": _p("Core Foundations", "core", [_i("plank",3,45,30), _i("deadbug",3,10,30), _i("bird",3,10,30), _i("splank",3,30,30)]),
    "core_adv": _p("Advanced Core", "core", [_i("toesbar",3,8,60), _i("abwheel",3,10,60), _i("pallof",3,12,45), _i("hollow",3,30,30), _i("dragon",3,5,60)]),
    "mob_daily": _p("Daily Mobility Flow", "mobility", [_i("catcow",2,10,15), _i("worldgreat",2,5,15), _i("hipflex",2,30,15), _i("hamstretch",2,30,15), _i("chestopen",2,30,15)]),
    "mob_hips": _p("Hip Mobility Focus", "mobility", [_i("ninenine",2,45,15), _i("pigeon",2,45,15), _i("couch",2,45,15), _i("worldgreat",2,5,15)]),
    "mob_shoulders": _p("Shoulder and T-Spine Mobility", "mobility", [_i("banddisloc",2,12,15), _i("thread",2,8,15), _i("chestopen",2,30,15), _i("scapula",2,10,15)]),
    "home_no_equip": _p("Home — No Equipment", "strength", [_i("pushup",4,12,45), _i("squatjump",3,10,45), _i("invrow",3,10,60), _i("lunge",3,12,45), _i("plank",3,40,30), _i("burpee",3,8,45)]),
    "home_db_only": _p("Home — Dumbbells Only", "strength", [_i("gsq",4,10,60), _i("dbbp",3,10,90), _i("dbrow",3,10,60), _i("dohp",3,10,60), _i("rdl",3,10,90), _i("dbcurl",2,12,45)]),
    "hotel": _p("Hotel Room Quick", "strength", [_i("pushup",3,15,30), _i("squatjump",3,12,30), _i("mountain",3,20,30), _i("plank",2,45,20), _i("burpee",2,10,30)]),
    "athlete_saq": _p("Speed and Agility Primer", "plyo", [_i("sprint",6,1,90), _i("skater",4,8,45), _i("latbound",4,6,45), _i("boxjump",4,5,60)]),
    "strongman_lite": _p("Strongman Lite", "strength", [_i("farmers",4,40,90), _i("trapbar",4,5,150), _i("ohp",3,5,120), _i("kbswing",3,15,60)]),
    "deload_full": _p("Deload Full Body", "strength", [_i("sq",3,5,120), _i("bp",3,5,120), _i("row",3,8,90), _i("rdl",2,8,90)]),
    "rehab_knee": _p("Knee-Friendly Lower", "strength", [_i("legpress",3,12,90), _i("legcurl",3,12,60), _i("hipthrust",3,12,60), _i("calfraise",3,15,45), _i("wallsit",2,30,45)]),
    "rehab_shoulder": _p("Shoulder-Friendly Upper", "strength", [_i("dbbp",3,10,90), _i("cblerow",3,12,60), _i("facepull",4,15,45), _i("latraise",3,12,45), _i("triceps",3,12,45)]),
    "women_glute": _p("Glute and Lower Shape", "strength", [_i("hipthrust",4,12,90), _i("bsq",3,10,90), _i("rdl",3,10,90), _i("cablekick",3,15,45), _i("legabduct",3,15,45), _i("calfraise",3,15,45)]),
    "tactical": _p("Tactical Conditioning", "plyo", [_i("burpee",5,10,45), _i("farmers",4,40,60), _i("sprint",5,1,60), _i("pullup",4,6,60), _i("kbswing",4,15,45)]),
    "morning_flow": _p("Morning Activation", "mobility", [_i("catcow",2,10,10), _i("bird",2,8,15), _i("worldgreat",2,5,15), _i("plank",2,30,20), _i("walk",1,10,0)]),
    "finisher_abs": _p("Ab Finisher", "core", [_i("crunch",3,15,30), _i("bicycle",3,20,30), _i("legraise",3,10,45), _i("plank",2,45,30)]),
    "finisher_cond": _p("Conditioning Finisher", "aerobic", [_i("abike",5,30,30), _i("burpee",3,8,30)]),
    "bro_chest_tri": _p("Bro Split — Chest and Triceps", "strength", [_i("bp",4,8,90), _i("idbbp",3,10,90), _i("cablefly",3,12,60), _i("triceps",3,12,60), _i("skull",3,12,60)]),
    "bro_back_bi": _p("Bro Split — Back and Biceps", "strength", [_i("pullup",4,8,90), _i("row",4,8,90), _i("latpd",3,10,60), _i("curl",3,12,45), _i("hamcurl",3,12,45)]),
    "bro_shoulders": _p("Bro Split — Shoulders", "strength", [_i("ohp",4,8,90), _i("latraise",4,15,45), _i("reardelt",3,15,45), _i("shrug",3,12,60), _i("facepull",3,15,45)]),
    "bro_legs": _p("Bro Split — Legs", "strength", [_i("sq",4,8,120), _i("rdl",3,10,90), _i("legpress",3,12,90), _i("legext",3,15,60), _i("legcurl",3,12,60), _i("calfraise",4,15,45)]),
}

FOODS = [
    {"id": "chicken", "name": "Chicken Breast (cooked)", "cal": 165, "protein": 31, "carb": 0, "fat": 3.6},
    {"id": "rice", "name": "White Rice (cooked)", "cal": 130, "protein": 2.7, "carb": 28, "fat": 0.3},
    {"id": "oats", "name": "Oats (dry)", "cal": 389, "protein": 17, "carb": 66, "fat": 7},
    {"id": "egg", "name": "Whole Egg", "cal": 155, "protein": 13, "carb": 1.1, "fat": 11},
    {"id": "salmon", "name": "Salmon (cooked)", "cal": 208, "protein": 20, "carb": 0, "fat": 13},
    {"id": "broccoli", "name": "Broccoli", "cal": 34, "protein": 2.8, "carb": 7, "fat": 0.4},
    {"id": "banana", "name": "Banana", "cal": 89, "protein": 1.1, "carb": 23, "fat": 0.3},
    {"id": "milk", "name": "Milk (2%)", "cal": 50, "protein": 3.3, "carb": 4.8, "fat": 2},
    {"id": "greek", "name": "Greek Yogurt (plain)", "cal": 59, "protein": 10, "carb": 3.6, "fat": 0.4},
    {"id": "almond", "name": "Almonds", "cal": 579, "protein": 21, "carb": 22, "fat": 50},
    {"id": "sweetpotato", "name": "Sweet Potato (baked)", "cal": 90, "protein": 2, "carb": 21, "fat": 0.2},
    {"id": "beef", "name": "Lean Ground Beef (90%)", "cal": 176, "protein": 20, "carb": 0, "fat": 10},
    {"id": "whey", "name": "Whey Protein Scoop", "cal": 120, "protein": 24, "carb": 3, "fat": 1},
    {"id": "avocado", "name": "Avocado", "cal": 160, "protein": 2, "carb": 9, "fat": 15},
    {"id": "oliveoil", "name": "Olive Oil (tbsp)", "cal": 119, "protein": 0, "carb": 0, "fat": 13.5},
    {"id": "tuna", "name": "Tuna (canned in water)", "cal": 116, "protein": 26, "carb": 0, "fat": 1},
    {"id": "quinoa", "name": "Quinoa (cooked)", "cal": 120, "protein": 4.4, "carb": 21, "fat": 1.9},
    {"id": "apple", "name": "Apple", "cal": 52, "protein": 0.3, "carb": 14, "fat": 0.2},
    {"id": "pb", "name": "Peanut Butter", "cal": 588, "protein": 25, "carb": 20, "fat": 50},
    {"id": "spinach", "name": "Spinach (raw)", "cal": 23, "protein": 2.9, "carb": 3.6, "fat": 0.4},
]


def food_by_id(fid: str):
    for f in FOODS:
        if f["id"] == fid:
            return f
    return None
